name: Deploy React App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # hoặc phiên bản Node.js phù hợp với dự án của bạn

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: npm run build && npm run deploy